
flib_version=0.2.8
flib_file=8482026
modrinth_id=

mod_id=nolavabuild
curse_id=333828
mod_version=1.0.3
curse_slug=cannot-build-over-lava-source-blocks
mod_name=nolavabuild
mod_group_id=com.lothrazar.nolavabuild
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
